// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kDzTm611hpBO6K67ORcj8wG496epxBI',
    appId: '1:724394569162:web:54e7a6aa85c5de52f03333',
    messagingSenderId: '724394569162',
    projectId: 'chatsphere-198e6',
    authDomain: 'chatsphere-198e6.firebaseapp.com',
    storageBucket: 'chatsphere-198e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiagZ9cSBDbkRFYhVFWJlQa_MyE9IqBME',
    appId: '1:724394569162:android:cdc7510e6703dd91f03333',
    messagingSenderId: '724394569162',
    projectId: 'chatsphere-198e6',
    storageBucket: 'chatsphere-198e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsPsr0Kp1vztRTRphv4YdU27-AvIE6llU',
    appId: '1:724394569162:ios:a318b1e802024717f03333',
    messagingSenderId: '724394569162',
    projectId: 'chatsphere-198e6',
    storageBucket: 'chatsphere-198e6.appspot.com',
    iosBundleId: 'com.example.chattingApplication',
  );
}
